version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  node-tests:
    jobs:
      node/test:
        working_directory: ~/project/12_optimize_efficiency/
        steps:
          - run: npm i
          - run: npm run build:split
        
